name: CI Workflow
# on: [push, pull_request]
on:
  issues:
    types: [opened]

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run my own composition action
        id: my-action
        uses: ./
        with:
          who-to-greet: '@ttteety'
      - name: Output the answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
